apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-app.fullname" . }}
  labels:
    {{- include "auth-app.labels" . | nindent 4 }}
data:
  ALGORITHM: {{ .Values.config.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  REFRESH_TOKEN_EXPIRE_DAYS: {{ .Values.config.refreshTokenExpireDays | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.config.googleRedirectUri | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}
  REDIS_URL: {{ include "auth-app.redisUrl" . | quote }}
